# Generated by Django 6.0.4 on 2026-05-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('voice', 'Voice'), ('ear_training', 'Ear Training')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('focus', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('mood', models.PositiveSmallIntegerField(default=3)),
                ('techniques', models.JSONField(blank=True, default=list)),
                ('songs_worked_on', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
