# Generated by Django 6.0.4 on 2026-05-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('title', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_song', models.CharField(blank=True, max_length=255)),
                ('exercises', models.JSONField(default=list)),
                ('completed_days', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
    ]
